/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 06-Mar-2026 11:56:49
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 4
 * Denominator Length  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
static const int highpass_NL = 4;
const float highpass_NUM[4] = {
		0.9949860584423,   -2.984958175327,    
		2.984958175327,  -0.9949860584423
};
static const int highpass_DL = 4;
const float highpass_DEN[4] = {
		1,   -2.989946914092,
		2.979944296952,  -0.9899972564945
};
