/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 06-Mar-2026 11:54:58
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 4
 * Denominator Length  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024b\extern\include\tmwtypes.h 
 */
const int NL = 4;
const real64_T NUM[4] = {
  3.756838019751e-06,1.127051405925e-05,1.127051405925e-05,3.756838019751e-06
};
const int DL = 4;
const real64_T DEN[4] = {
                   1,    -2.93717072845,    2.876299723479,  -0.9390989403253
};
